services:
  db_pg:
    image: postgres
    container_name: db_pg
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: .
    ports: 
      - 5000:5000
    depends_on:
      - db_pg
    env_file:
      - .env.test
